# Generated by Django 6.0.6 on 2026-07-21 16:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(help_text='Represents the full name of the author.', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('email', models.EmailField(help_text='Represents the email address of the author.', max_length=254, unique=True)),
                ('is_banned', models.BooleanField(default=False, help_text='Indicates whether the author is currently banned.')),
                ('birth_year', models.PositiveIntegerField(help_text='Represents the year of birth of the author.', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2005)])),
                ('website', models.URLField(blank=True, help_text="Represents the URL of the author's website.", null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Represents the title of the article.', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('content', models.TextField(help_text='Provides the content of the article.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Science', 'Science'), ('Education', 'Education')], default='Technology', help_text='Represents the category of the article.', max_length=10)),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('authors', models.ManyToManyField(related_name='articles', to='main_app.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.author')),
            ],
        ),
    ]
