# Generated by Django 6.0.6 on 2026-07-19 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(help_text='Represents the name of the product.', max_length=100)),
                ('description', models.TextField(help_text='Provides a detailed description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Represents the price of the product.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('in_stock', models.PositiveIntegerField(help_text='Represents the quantity of the product in stock.')),
                ('is_available', models.BooleanField(default=True, help_text='Indicates whether the product is currently available for purchase.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(help_text='Represents the full name of the user.', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('email', models.EmailField(help_text='Represents the email address of the user.', max_length=254)),
                ('phone_number', models.CharField(help_text='This field is typically a string to accommodate various phone number formats.', max_length=15)),
                ('address', models.TextField(help_text='This field can store longer text, suitable for addresses.')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the profile is active or not.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Represents the total price of the order.', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates whether the order has been completed or not.')),
                ('products', models.ManyToManyField(related_name='orders', to='main_app.product')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main_app.profile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
