# Generated by Django 6.0.5 on 2026-06-03 04:54
import random
from django.db import migrations

def add_barcode(apps, shema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()
    all_barcode = random.sample(
        range(100_000_000, 1_000_000_000),
        len(all_products))
    for i in range(len(all_barcode)):
        product = all_products[i]
        product_barcode = all_barcode[i]
        product.save()

def reverse_add_barcode(apps, shema_editor):
    Product = apps.get_model('main_app', 'Product')
    for product in Product.object.all():
        product.barcode = 0
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_created_on_product_last_edited_on'),
    ]

    operations = [
        migrations.RunPython(add_barcode, reverse_add_barcode)
    ]
