# Generated by Django 6.0.6 on 2026-07-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='DiscountedProduct',
        ),
    ]
