# Generated by Django 6.0.5 on 2026-06-04 18:44

from django.db import migrations, models

def create_age_group(apps, schema_editor):
    person = apps.get_model('main_app', 'Person')
    ages = person.object.all()

    for curr_age in ages:
        if curr_age <= 12:
            age_group = 'Child'
        elif 13 <= curr_age <= 17:
            age_group = 'Teen'
        else:
            age_group = 'Adult'

        curr_age.age = age_group
        curr_age.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.PositiveIntegerField()),
                ('age_group', models.CharField(default='No age group', max_length=20)),
            ],
        ),
    ]
