# Generated by Django 6.0.5 on 2026-06-05 11:13

from django.db import migrations, models
from datetime import timedelta

def create_delivery_status(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    orders = Order.objects.all()

    for order in orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days = 3)

        elif order.status == 'Completed':
            order.warranty = '24 months'

        elif order.status == 'Cancelled':
            order.delete()
            continue
    
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_smartphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('customer_name', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=30)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('warranty', models.CharField(default='No warranty', max_length=264)),
                ('delivery', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RunPython(create_delivery_status)
    ]
