# Generated by Django 6.0.6 on 2026-07-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='main_app_do_search__6fe248_gin',
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['search_vector'], name='main_app_do_search__c97410_idx'),
        ),
    ]
