# Generated by Django 6.0.5 on 2026-06-04 18:53

from django.db import migrations, models

def create_rarity_groups(apps, schema_editor):
    Item = apps.get_model('main_app', 'Item')
    items = Item.objects.all()

    for item in items:
        price = item.price

        if price <= 10:
            item_rarity = 'Rare'
        elif 11 <= price <= 20:
            item_rarity = 'Very Rare'
        elif 21 <= price <= 30:
            item_rarity = 'Extremely Rare'
        else:
            item_rarity = 'Mega Rare'

        item.rarity = item_rarity
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rarity', models.CharField(default='No rarity', max_length=20)),
            ],
        ),
    ]
