# Generated by Django 6.0.5 on 2026-06-04 19:04

from django.db import migrations, models

def update_price_per_length(apps, schema_editor):
    Price = apps.get_model('main_app', 'Smartphone')
    phones = Price.objects.all()

    for phone in phones:
        new_price = len(phone.brand) * 120

        phone.price= new_price
        phone.save()

def update_category(apps, schema_editor):
    Smartphone = apps.get_model('main_app', 'Smartphone')
    phones = Smartphone.objects.all()

    for phone in phones:
        curr_price = phone.price

        if curr_price < 750:
            cat_group = 'Cheap'
        else:
            cat_group = 'Expensive'

        phone.category = cat_group
        phone.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(default='No category', max_length=20)),
            ],
        ),
        migrations.RunPython(update_price_per_length),
    ]
