"""Added recipe model

Revision ID: 17d5b78046dc
Revises: 8ce00af83c9c
Create Date: 2026-07-29 06:55:29.097033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d5b78046dc'
down_revision: Union[str, Sequence[str], None] = '8ce00af83c9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('instructions', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'instructions')
    # ### end Alembic commands ###
