"""Added Chef model and relationship with Recipe

Revision ID: a3beb012800b
Revises: 17d5b78046dc
Create Date: 2026-07-29 08:01:07.644269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3beb012800b'
down_revision: Union[str, Sequence[str], None] = '17d5b78046dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('recipe', sa.Column('chef_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipe', 'chefs', ['chef_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_column('recipe', 'chef_id')
    op.drop_table('chefs')
    # ### end Alembic commands ###
